### ISSUE TITLE
Align shoot resource schema with the gardener shoot crd

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/terraform-provider-gardener#17]
**Description**
A shoot resource as implemented at the moment looks quite different than the shoot CRD of gardener project.  Please adjust the schema to be the same as in the CRD and assure that it is complete.

**Reasons**
Avoid confusion, someone knowing the gardener API should be able to use the terraform plugin out of the box, even by copy/pasting things.

**Comment by obadrawi** [comment]
The schema has been changed to match the gardener shoot schema
