### ISSUE TITLE
Re-applying a shoot causes many changes

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/terraform-provider-gardener#27]
**Description**
Follow the examples and apply the plan. After cluster creation just apply the plan again. You will see that the plan contains a lot of modifications.

**Expected result**
No modifications are outlines to the plan as long as nothing changed locally or remote

**Actual result**
Looks like the generated attributes on server side are treated as modification

**Steps to reproduce**
Call "terraform apply" twice

**Comment by obadrawi** [comment]
Fixed in PR #29
