### ISSUE TITLE
Switch to core.gardener.cloud/v1beta1 API group

### ISSUE THREAD

**Issue by ialidzhikov** [kyma-incubator/terraform-provider-gardener#34]
**Description**
Currently kyma-incubator/terraform-provider-gardener consumes the old and deprecated `garden.sapcloud.io/v1beta1` API group which soon will reach end of life.
Since [gardener/gardener@0.30.0](https://github.com/gardener/gardener/releases/tag/0.30.0) there is `core.gardener.cloud/v1alpha1` and since [gardener/gardener@v0.33.0](https://github.com/gardener/gardener/releases/tag/v0.33.0) there is `core.gardener.cloud/v1beta1`.

**Comment by a-thaler** [comment]
Thanks for the feedback, we will update to the new versions

**Comment by neo-liang-sap** [comment]
i will take look at this issue :)

**Comment by neo-liang-sap** [comment]
Hi @a-thaler / @ialidzhikov :

Not sure i'm understanding correctly and heading correct approach, this issue means refactor reference in `terraform-provider-gardener` from `garden.sapcloud.io/v1beta1` to `core.gardener.cloud/v1beta1`

Is there anything else i need to take care of?

If i'm right i have prepared the PR, correct me if i was wrong...
https://github.com/kyma-incubator/terraform-provider-gardener/pull/38

Thanks!

-Neo

**Comment by neo-liang-sap** [comment]
PR in this issue is reverted by https://github.com/kyma-incubator/terraform-provider-gardener/pull/42

some more info - https://listserv.sap.corp/pipermail/kubernetes-users/2019-October/000692.html

**Comment by a-thaler** [comment]
All three providers (AWS, GCP, Azure) are supported now as before
