### ISSUE TITLE
Adding feature of "Monitoring" and "cabundle" configuration in tf provider for gardener

### ISSUE THREAD

**Issue by neo-liang-sap** [kyma-incubator/terraform-provider-gardener#35]
Hello,

This is Neo Liang from Gardener SRE team, currently i'm based in Shanghai China.

We Gardener SRE team use tf provider for Gardener to build shoot cluster to some of our internal customers.

We had an internal discussion to compare api/properties/configuration exposed by Gardener API and TF Provider of Gardener and we found following two items are not exposed:

1) Monitoring - https://github.com/gardener/gardener/blob/master/pkg/apis/core/v1beta1/types_shoot.go#L82

This is supported in Gardener shoot build as code above but we didn't find this information in TF Provider of Gardener

2) cabundle - https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L54

In the sample yaml of building an shoot there's one configuration of cabundle but i didn't find it in TF Provider of Gardener

We hope these two items could be added.

Do let me know if i didn't understand correctly on the two issues i mentioned e.g. they are implemented in somewhere i didn't find it or i misunderstand the usage of them.....apology in advance ;)

i'm linking our leader @dansible (Daniel Pacrami daniel.pacrami@sap.com) here for more discussion.

Thanks!

-Neo

**Comment by a-thaler** [comment]
yep, the attributes should be added, thanks for the feedback

**Comment by neo-liang-sap** [comment]
Hi @a-thaler :
Thanks for the comments! i tried to implement this issue in my forked repo and i drafted PR https://github.com/neo-liang-sap/terraform-provider-gardener/pull/1

Could you please review it when you have time?

Thanks again!

CC @dansible 

-Neo

**Comment by a-thaler** [comment]
Thanks for supporting us here. Can you please create a PR against the master branch of this repo here (not the master of the fork), then anyone of the team can review it and the CI will kick in as well.

**Comment by neo-liang-sap** [comment]
thanks! the PR is opened here https://github.com/kyma-incubator/terraform-provider-gardener/pull/37

**Comment by a-thaler** [comment]
Feature added by https://github.com/kyma-incubator/terraform-provider-gardener/pull/37
