### ISSUE TITLE
Automated release

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/terraform-provider-gardener#46]
**Description**
At the moment a new release needs to get created manual, especially the binary is build on a local machine and uploaded.

Have an automation based on prow for building and uploading the release artifacts, similar to the CLI project.

Have the process documented in a dedicated MD file

**Reasons**
Humans are doing mistakes, every local machine is different, reproducability

**Attachments**

**Comment by kayrus** [comment]
@a-thaler we managed to release our Terraform provider under Terraform registry. See an example here: https://github.com/sapcc/terraform-provider-ccloud/commit/fc9d282279efd6c189a07f1f42e05d084950e0ba
https://registry.terraform.io/providers/sapcc/ccloud/latest/docs

The only issue we faced, the release haven't built for the first time, because we pushed the commit along with the tag. So you need to push the commit with the github releaser changes and only then make a new tag

**Comment by a-thaler** [comment]
Thanks for sharing the feedback with us!

Actually, we are thinking about testing a bit more https://github.com/hashicorp/terraform-provider-kubernetes-alpha and switching to it as soon as it is in beta as it should cover our needs. so probably we will archive the project and the publishing will not be required. Will close the ticket for now.

Anyway really nice that you took the time to provide the feedback!

**Comment by kayrus** [comment]
@a-thaler not sure how is it connected to a gardener project and its API

**Comment by a-thaler** [comment]
@kayrus Gardener has a well-defined API fully based on kubernetes CRDs. The current terraform provider here transforms the terraform manifest into gardener resource definitions and uses the kubernetes client to apply the resources. The same can be achieved by using the https://github.com/hashicorp/terraform-provider-kubernetes. That would safe the maintenance effort and any change on the gardener API (like new features) will be available immediately.
Unfortunately, the current kubernetes provider does not support CRDs yet, so there is no way to make use of it yet.
Luckily it is being worked on a new version which brings CRD support, see https://github.com/hashicorp/terraform-provider-kubernetes-alpha. I did a simple test already and it worked for me to create a shoot via this provider by just placing the shoot spec into the manifest. Having that would also mean to have support for all other Gardener CRDs like project members out of the box.

So we need to test it properly if it will be a good replacement, wait for a beta version and then provide some examples in the gardener project on how to use it.

Does it make sense for you or do you see potential problems with that plan?

**Comment by kayrus** [comment]
@a-thaler no issues, thanks for a clarification.
