### ISSUE TITLE
Add automatic tests

### ISSUE THREAD

**Issue by pzamzow** [kyma-incubator/terraform-provider-gardener#55]
**Description**
At the moment the provider does not have any automatic unit or acceptance tests. Terraform has a build-in [testing framework](https://www.terraform.io/docs/extend/best-practices/testing.html), which should be adopted to keep the provider stable in the future. As a first step unit tests should be sufficient. But in the end automatic acceptance tests, which create real infrastructure during the tests, should prevent regressions.

When the automatic tests are executed, the code coverage should be measured and checked. GO has support for this build-in (see [here](https://blog.golang.org/cover)). Unfortunately the current package structure would not allow an accurate coverage result, because GO tools are not working well with multiple packages (issue is described [here](https://www.ory.sh/golang-go-code-coverage-accurate/)). Therefore the tool mentioned in the article needs to be used or the package structure needs be adopted. In the end the CI infrastructure should not allow new code, which is not covered by a test.

**Comment by clebs** [comment]
Hi @pzamzow,
thanks for reporting this issue. It is true that there is a lack of tests in this provider and we definitely must add them soon.
The idea you propose using the terraform testing framework to do infrastructure tests would be great together with the unit tests.

Regarding the coverage, we are already measuring test coverage on other Go repos we have (for example https://github.com/kyma-project/cli) also based on the article you mention. We would add that coverage as well as soon as there are tests on this repo.

We will add this issue to our backlog, keep track of it and work on it as soon as possible.

**Comment by a-thaler** [comment]
We plan to not continue the project, see https://github.com/kyma-incubator/terraform-provider-gardener/issues/83
