### ISSUE TITLE
Provider is hard to maintain 

### ISSUE THREAD

**Issue by pzamzow** [kyma-incubator/terraform-provider-gardener#61]
**Description**
In my opinion the current project structure does not make it easy to maintain the provider with a certain quality. Besides the missing tests (#55) the structure of the project itself makes it hard to ensure that the [schema](https://github.com/kyma-incubator/terraform-provider-gardener/blob/master/shoot/schema_shoot.go) of the provider, [expand](https://github.com/kyma-incubator/terraform-provider-gardener/blob/master/expand/expand_spec.go) and [flatten](https://github.com/kyma-incubator/terraform-provider-gardener/blob/master/flatten/flatten_spec.go) are all working on the same assumptions. Therefore I propose the following new structure: https://github.com/pzamzow/terraform-provider-gardener/tree/structure/gardener

**Reasons**
The main tasks of the provider is basically defining a HCL schema and converting this from/ to the Gardener structure. To implement this you need to work with the files above, which are all 300+ or 700+ lines of code. So it is very hard during development to ensure that all of this matches together. It is not easy to see, that there is some mismatch.

With the new structure it is easy to see that the following is wrong:
- https://github.com/pzamzow/terraform-provider-gardener/blob/structure/gardener/structure_cluster_autoscaler.go
- https://github.com/pzamzow/terraform-provider-gardener/blob/structure/gardener/structure_kube_api_server.go
- https://github.com/pzamzow/terraform-provider-gardener/blob/structure/gardener/structure_kube_controller_manager.go
- https://github.com/pzamzow/terraform-provider-gardener/blob/structure/gardener/structure_kubelet.go
- https://github.com/pzamzow/terraform-provider-gardener/blob/structure/gardener/structure_kubernetes.go

The list above are all examples of the current state of the provider, where schema, flatten and expand do not match.  It is almost impossible to figure this out with the current structure.

In addition I would recommend to put everything into a single package. This seems to be best practice also at other providers. It also makes the calculation of a test coverage easier (see #55). At the moment there are multiple packages with just a single file in it. 

Testing is also easier with the new structure because you can write unit tests for the individual components instead of always testing the hole `shoot` schema.

I agree, that the new structure has a lot of files, which might look more complex on a first view. But it helps a lot when developing the individual parts of the Gardener structure. To navigate between the individual files the IDEs help a lot and even GitHub can navigaten between the references (e.g. click on `KubeControllerManagerResource` [here](https://github.com/pzamzow/terraform-provider-gardener/blob/structure/gardener/structure_kubernetes.go#L28)) ([learn more](https://help.github.com/en/github/managing-files-in-a-repository/navigating-code-on-github)).

Please let me know, what you thing about the new structure and if we should develop into this direction.

**Comment by pzamzow** [comment]
@a-thaler could you please discuss this internally and let me know what you think about it?

**Comment by clebs** [comment]
Hi @pzamzow,

we are aware that many official Providers do use this kind of flat structure and have everything in one package. We considered this structure but in the end tried to keep things a bit more easy to navigate by having packages for each piece of the provider.

The concept I had in mind when we started is that each resource (e.g. shoot) would have its own package with different files (and tests) for each of its parts (flatten, expand, shoot itself, etc...).
Even sub-resources could then be subpackages of shoot, with their own files for each part.
At least from my limited experience with this, it sounds like a solid design.

What I see though is that the structure degraded over time due to not following the package design (e.g. there should be not a `flatten` root level package with flatten for all resources), so certainly the packages we have right now are just not correct.

I would propose that we find a good design that solves the issues you mention and makes sense while trying to avoid the single massive package.

What do you think?

**Comment by pzamzow** [comment]
@clebs I am also fine with a more fine granular directory structure, but I would like to avoid packages with just a single file in it. The [azure provider](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services) for example also has a deep directory structure. 

The gardener provider on the other hand is a bit different, because the `shoot` resource is very big with a complex schema. Therefore my suggestion to split it into smaller sub-structures. As you see in my proposed structure ([here](https://github.com/pzamzow/terraform-provider-gardener/tree/structure/gardener)) the sub-structures are then very small, so that you can put `expand`, `flatten` and `schema` into a single file. This also helps to find differences between them.  If you would now create sub-directories for each sub-structure, you end up with two files in each directory. I am not sure if this helps.

**Comment by clebs** [comment]
Hi @pzamzow,

great, then we agree! Let's find a structure that serves us well and get a good middle point between what we have now and a single package.

**Comment by pzamzow** [comment]
@clebs I pushed a new proposal [here](https://github.com/pzamzow/terraform-provider-gardener/tree/structure). Please have a look and let me know if this works for your.

**Comment by clebs** [comment]
Hi @pzamzow,
Thanks for the proposal! I will have a look when I have some time.

**Comment by a-thaler** [comment]
We plan to not continue the project, see https://github.com/kyma-incubator/terraform-provider-gardener/issues/83
