### ISSUE TITLE
Add support for controlplane_config for AWS.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-incubator/terraform-provider-gardener#64]
**Description**

Currently the support for `controlplane_config` is missing for AWS. We should add this for feature completeness. Although its possible to create an AWS gardener cluster without control plane config.

**Comment by neo-liang-sap** [comment]
i will add control_plane_config after https://github.com/kyma-incubator/terraform-provider-gardener/pull/63 is merged - to follow structure and avoid conflict

**Comment by neo-liang-sap** [comment]
https://github.com/kyma-incubator/terraform-provider-gardener/pull/65

**Comment by neo-liang-sap** [comment]
the PR working for this ticket is in https://github.com/kyma-incubator/terraform-provider-gardener/pull/68

**Comment by neo-liang-sap** [comment]
close issue as PR MERGED
