### ISSUE TITLE
Adding additional worker group via Terraform gives error

### ISSUE THREAD

**Issue by pavanasamr** [kyma-incubator/terraform-provider-gardener#84]
Hi Team,

We have created Gardener cluster via Terraform. But when we try to add additional worker group via Terraform, we're getting below error.

but the gkr-2 cluster is already exists. https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-cobalt-dev/shoots/gkr-2/
can you please check why we’re getting this error?

```Error: the server could not find the requested resource (get shoots.core.gardener.cloud gkr-2)

  with gardener_shoot.shoot_cluster,
  on shoot_cluster.tf line 8, in resource "gardener_shoot" "shoot_cluster":
   8: resource "gardener_shoot" "shoot_cluster" {```

**Comment by a-thaler** [comment]
Hi @pavanasamr, the provider is not really maintained in recent time and was focused from the beginning on simple use cases. We are thinking about discontinuing this terraform project, see also https://github.com/kyma-incubator/terraform-provider-gardener/issues/83.

**Comment by a-thaler** [comment]
will close the issue, see the reasoning above
